apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-hub-browser.fullname" . }}
  labels:
    app: {{ include "event-hub-browser.name" . }}
    chart: {{ include "event-hub-browser.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "event-hub-browser.name" . }}
    release: {{ .Release.Name }}
