{{- if .Values.istio.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "event-hub-browser.fullname" . }}
  labels:
    app: {{ include "event-hub-browser.name" . }}
    chart: {{ include "event-hub-browser.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  gateways:
{{ toYaml .Values.istio.virtualService.gateways | indent 2 -}}
  hosts:
{{ toYaml .Values.istio.virtualService.hosts | indent 2 -}}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.virtualService.path | quote }}
{{- if .Values.istio.virtualService.rewrite }}
    rewrite:
      uri: {{ .Values.istio.virtualService.rewrite | quote }}
{{- end }}
    route:  
    - destination:
        host: {{ include "event-hub-browser.fullname" . }}
        port:
          number: 80
{{- end }}